---
title: "ALS_initial_research"
author: "Tetyana Yatsenko"
date: "2023-03-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(!require(dplyr)) install.packages("dplyr")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(xtable)) install.packages("xtable")
if(!require(devtools)) install.packages("devtools")

library(dplyr)
library(devtools)
library(ggplot2)
library(xtable)
```

## Read ALS Data


```{r}

workdir <- getwd() 

finenameALSFRS <- "PROACT_ALSFRS.csv"
finenameDeath <- "PROACT_DEATHDATA.csv"
finenameRiluzole <- "PROACT_RILUZOLE.csv"


alsrfs <-  read.csv(file = paste(workdir,finenameALSFRS,sep="/"))
alsrfs$subject_id <- as.factor(alsrfs$subject_id)
print(str(alsrfs))

deathdata <-  read.csv(file = paste(workdir,finenameDeath,sep="/"))
deathdata$subject_id <- as.factor(deathdata$subject_id)
print(str(deathdata))

riluzole <-  read.csv(file = paste(workdir,finenameRiluzole,sep="/"))
riluzole$subject_id <- as.factor(riluzole$subject_id)
print(str(riluzole))



impotantcolumns1 <- c("subject_id","ALSFRS_Delta","ALSFRS_R_Total")
impotantcolumns2 <- c("subject_id","ALSFRS_Delta","avg_ALSFRS_R_Total")
```

## Death Data
```{r}

# subject_id is not unique here. 
# it is one person with two death date, i will choose the last
filter_deathdata <- 
  deathdata  %>% 
  unique() %>%
  group_by(subject_id,Subject_Died) %>%
  summarise(Death_Days_max = max(Death_Days)) %>%
  ungroup()

colnames(filter_deathdata)[colnames(filter_deathdata) == "Death_Days_max"] = "Death_Days"



print(str(filter_deathdata))  

```

## Riluzole  Data
```{r}
# subject_id is unique here. I have checked
filter_riluzole <- 
  riluzole  %>% 
  unique() 

print(str(filter_riluzole))


```

## ALSRFRS  Data
```{r}

# select columns "subject_id","ALSFRS_Delta","ALSFRS_R_Total"
# filter rows with values in columns "ALSFRS_Delta","ALSFRS_R_Total"
# average value of "ALSFRS_R_Total" in a certain in moment of time
# we have several records some time


filter_alsrfs <- 
     alsrfs %>% 
     select(impotantcolumns1) %>% 
     filter(!is.na(ALSFRS_R_Total)) %>%
     filter(!is.na(ALSFRS_Delta))  %>%
     group_by(subject_id, ALSFRS_Delta) %>%
     summarise(avg_ALSFRS_R_Total = mean(ALSFRS_R_Total)) %>%
     select(impotantcolumns2) %>%
     ungroup() 
    

colnames(filter_alsrfs)[colnames(filter_alsrfs) == "avg_ALSFRS_R_Total"] = "ALSFRS_R_Total"
filter_alsrfs$ALSFRS_R_Total <- round( filter_alsrfs$ALSFRS_R_Total )

print(str(filter_alsrfs))

```

## Original statistics preparation
```{r}
# Calculate simple statistics: number of measurement (visits), day of first visit, last visit
# time between first and last visit days, weeks, months
stat_filter_alsrfs <- 
   filter_alsrfs %>%
   group_by(subject_id) %>%
   summarise( Number_visits = n(), 
              first_visit = min(ALSFRS_Delta), 
              last_visit = max(ALSFRS_Delta), 
              time_interval_days = 1+max(ALSFRS_Delta) - min(ALSFRS_Delta) ) 


stat_filter_alsrfs$first_visit_weeks <- round( stat_filter_alsrfs$first_visit / 7.0 )
stat_filter_alsrfs$first_visit_months <- round( stat_filter_alsrfs$first_visit / 30.0 )

stat_filter_alsrfs$last_visit_weeks <- round( stat_filter_alsrfs$last_visit / 7.0 )
stat_filter_alsrfs$last_visit_months <- round( stat_filter_alsrfs$last_visit / 30.0 )

stat_filter_alsrfs$time_interval_weeks <- round( stat_filter_alsrfs$time_interval_days / 7.0 )
stat_filter_alsrfs$time_interval_months <- round( stat_filter_alsrfs$time_interval_days / 30.0 )


# Add value of ALSFRS_R in the first measurement
stat_filter_alsrfs <- 
     stat_filter_alsrfs  %>%
     inner_join(filter_alsrfs, by=c("subject_id" = "subject_id", "first_visit" =  "ALSFRS_Delta")) %>%
     unique()
   
colnames(stat_filter_alsrfs)[colnames(stat_filter_alsrfs) == "ALSFRS_R_Total"] = "intial_ALSFRS_R_Total"

# Add value of ALSFRS_R in the last measurement
stat_filter_alsrfs <- 
     stat_filter_alsrfs  %>%
     inner_join(filter_alsrfs, by=c("subject_id" = "subject_id", "last_visit" =  "ALSFRS_Delta")) %>%
     unique()

colnames(stat_filter_alsrfs)[colnames(stat_filter_alsrfs) == "ALSFRS_R_Total"] = "last_ALSFRS_R_Total"

print(str(stat_filter_alsrfs))


```
## Merge death 
```{r}
stat_filter_alsrfs <-
  stat_filter_alsrfs  %>%
  left_join(filter_deathdata, by=c("subject_id" = "subject_id"))

#left_join(filter_deathdata, by=c("subject_id" = "subject_id"))

#stat_filter_alsrfs$Subject_Died[is.na(stat_filter_alsrfs$Subject_Died)] <- "No"

# Add   censored time of death,days (near 275 cases)
stat_filter_alsrfs$Death_Days[ stat_filter_alsrfs$Subject_Died=="Yes" & 
                              is.na(stat_filter_alsrfs$Death_Days) ] <- 
  stat_filter_alsrfs$last_visit[ stat_filter_alsrfs$Subject_Died=="Yes" & 
                              is.na(stat_filter_alsrfs$Death_Days) ]

# Death time weeks, months
stat_filter_alsrfs$Death_weeks <- round( stat_filter_alsrfs$Death_Days / 7.0 )
stat_filter_alsrfs$Death_months <- round(stat_filter_alsrfs$Death_Days / 30.0 )

print(str(stat_filter_alsrfs))

print(unique(stat_filter_alsrfs$Subject_Died))

```
## Merge riluzole data
```{r}
stat_filter_alsrfs <-
  stat_filter_alsrfs  %>%
  left_join(filter_riluzole, by=c("subject_id" = "subject_id"))

stat_filter_alsrfs$Subject_used_Riluzole[is.na(stat_filter_alsrfs$Subject_used_Riluzole)] <- "No"
# Add start time of using Riluzole, for "Not" and "yes" without start time
stat_filter_alsrfs$Riluzole_use_Delta[is.na(stat_filter_alsrfs$Riluzole_use_Delta)] <- 0

stat_filter_alsrfs$Riluzole_use_Delta_weeks <- 
  round( stat_filter_alsrfs$Riluzole_use_Delta / 7.0 )
stat_filter_alsrfs$Riluzole_use_Delta_months <- 
  round( stat_filter_alsrfs$Riluzole_use_Delta / 30.0 )

print(str(stat_filter_alsrfs))

```
## Degradation, Slope
```{r}
# Changing of ALSFRS_R during all time
stat_filter_alsrfs$degradation <- stat_filter_alsrfs$last_ALSFRS_R_Total - stat_filter_alsrfs$intial_ALSFRS_R_Total

#More than one measurement + more than 1 month
stat_filter_alsrfs_op <- 
  stat_filter_alsrfs %>%
  filter(Number_visits>1) %>%
  filter(time_interval_months>0)
  

# Slope  of changing of ALSFRS_R during all time
stat_filter_alsrfs_op$slopedegradation <- 
  stat_filter_alsrfs_op$degradation / stat_filter_alsrfs_op$time_interval_months


filter_alsrfs <- 
  filter_alsrfs %>%
  mutate(ALSFRS_Delta_weeks = ALSFRS_Delta / 7.0) 
filter_alsrfs$ALSFRS_Delta_weeks <- round( filter_alsrfs$ALSFRS_Delta_weeks )

filter_alsrfs_st <-
  filter_alsrfs %>%
  inner_join(stat_filter_alsrfs, by=c("subject_id" = "subject_id")) 


filter_alsrfs_stop <-
  filter_alsrfs %>%
  inner_join(stat_filter_alsrfs_op, by=c("subject_id" = "subject_id")) 

print(str(stat_filter_alsrfs))
print(str(stat_filter_alsrfs_op))
print(str(filter_alsrfs_st))
print(str(filter_alsrfs_stop))
```

## Correlation 

```{r}

col <- c("Number_visits","time_interval_months","intial_ALSFRS_R_Total","last_ALSFRS_R_Total",
         "degradation","slopedegradation","Death_months", "Riluzole_use_Delta_months")

stat <- 
  filter_alsrfs_stop %>%
  select(col)

print(str(stat_correlation))

stat_correlation  <- cor(stat, use = "complete.obs")

print(stat_correlation)

```
## Dead & Riluzole stat
```{r}

Number_people <- dim( stat_filter_alsrfs)[1]

colnames <- c("Metric","Value", "Percentage")
r1 <- c("All people",dim( stat_filter_alsrfs)[1])

all <- dim(stat_filter_alsrfs)[1]
dead <- nrow(filter(stat_filter_alsrfs,stat_filter_alsrfs$Subject_Died == "Yes"))
alive <- nrow(filter(stat_filter_alsrfs,stat_filter_alsrfs$Subject_Died == "No"))

riluzole <- nrow(filter(stat_filter_alsrfs,stat_filter_alsrfs$Subject_used_Riluzole == "Yes"))
noRiluzole <- nrow(filter(stat_filter_alsrfs,stat_filter_alsrfs$Subject_used_Riluzole== "No"))

deadriluzole <- nrow(filter(stat_filter_alsrfs,stat_filter_alsrfs$Subject_Died == "Yes" &
                            stat_filter_alsrfs$Subject_used_Riluzole == "Yes"))
deadnoRiluzole <- nrow(filter(stat_filter_alsrfs,stat_filter_alsrfs$Subject_Died == "Yes" &
                            stat_filter_alsrfs$Subject_used_Riluzole == "No"))

aliveriluzole <- nrow(filter(stat_filter_alsrfs,stat_filter_alsrfs$Subject_Died == "No" &
                            stat_filter_alsrfs$Subject_used_Riluzole == "Yes"))
alivenoRiluzole <- nrow(filter(stat_filter_alsrfs,stat_filter_alsrfs$Subject_Died == "No" &
                            stat_filter_alsrfs$Subject_used_Riluzole == "No"))

metrics <- data.frame (
   Metric = c( "All people", "Dead", "Alive", "Riluzole", "noRiluzole", 
               "deadriluzole", "deadnoRiluzole", "aliveriluzole", "alivenoRiluzole"),
   Value = c( all, dead, alive, 
                   riluzole, noRiluzole, 
                   deadriluzole, deadnoRiluzole, 
                   aliveriluzole, alivenoRiluzole  ),
   Percentage =c(1, round(100.00*dead/all,2), round(100.00*alive/all,2), 
                   round(100.00*riluzole/all,2), round(100.00*noRiluzole/all,2),
                   round(100.00*deadriluzole/dead,2), round(100.00*deadnoRiluzole/dead,2), 
                   round(100.00*aliveriluzole/alive,2), round(100.00*alivenoRiluzole/alive,2) ),
   basePercetage = c (all, all, all, all, all, dead, dead, alive, alive)
   )

print(metrics)


```

## initial & last  ALFRS_R (Dead)
```{r pressure, echo=FALSE}

p1 <- ggplot(stat_filter_alsrfs_op, aes(x = intial_ALSFRS_R_Total, y = last_ALSFRS_R_Total)) +
  geom_point(size=2,aes(color = intial_ALSFRS_R_Total))

p3 <- p1 + facet_grid(Subject_Died~., margins = TRUE, scales='free', labeller=label_both)

show(p3)
```

## Histogram: Last ALSFRS_R

```{r pressure, echo=FALSE}

st <- 
  stat_filter_alsrfs %>%
  group_by(Subject_Died) %>%
  summarise(mean_last_ALSFRS_R_Total = mean(last_ALSFRS_R_Total), 
            median_last_ALSFRS_R_Total = median(last_ALSFRS_R_Total),
            max_last_ALSFRS_R_Total = max(last_ALSFRS_R_Total),
            min_last_ALSFRS_R_Total = min(last_ALSFRS_R_Total)
            ) %>%
  ungroup()
print(st)

p1 <- ggplot(stat_filter_alsrfs, aes(x =  last_ALSFRS_R_Total)) + 
  geom_histogram(color="blue", fill="lightblue", binwidth=1) 


p2 <- ggplot(stat_filter_alsrfs, aes(x =  last_ALSFRS_R_Total)) + 
  geom_histogram(aes(y=after_stat(density)), color="blue", fill="lightblue", binwidth=1)+
  geom_density(alpha=.2, fill="#FF6666") 

p3 <- p1 + facet_grid(Subject_Died~., margins = TRUE, scales='free', labeller=label_both)
p4 <- p2 + facet_grid(Subject_Died~., margins = TRUE, scales='free', labeller=label_both)


show(p3)
show(p4)


```
